function [a_index, b_index] = dialog_two_lists(dlg_title, ...
    a_title, a_options, a_default, ...
    b_title, b_options, b_default)

%     disp(nargin)
    if nargin == 5
        
    end

    dialog_height = 500; % px
    dialog_width = 600; % ps
    border = 20; % px
    text_height = 25; % ps
    
    d = dialog('Position',[300 100 dialog_width dialog_height],...
        'Name',dlg_title);
    
    uicontrol('Parent',d,...
           'Style','text',...
           'Position',[border dialog_height-text_height*2 ...
           dialog_width/2-1.5*border text_height],...
           'String', a_title);
   
    uicontrol('Parent',d,...
           'Style','text',...
           'Position',[dialog_width/2+0.5*border dialog_height-text_height*2 ...
           dialog_width/2-1.5*border text_height],...
           'String', b_title);
       
    uicontrol('Parent',d,...
           'Style','listbox',...
           'Position',[border text_height+2*border ...
           dialog_width/2-1.5*border dialog_height-(text_height+border*1.5)*2],...
           'String', a_options,...
           'Value', a_default,...
           'Max', 99, 'Min', 0,...
           'Callback',@popup_callback_x);
       
    uicontrol('Parent',d,...
           'Style','listbox',...
           'Position',[dialog_width/2+0.5*border text_height+2*border ...
           dialog_width/2-1.5*border dialog_height-(text_height+border*1.5)*2],...
           'String', b_options,...
           'Value', b_default,...
           'Max', 99, 'Min', 0,...
           'Callback',@popup_callback_y);
       
    uicontrol('Parent',d,...
           'Position',[border border dialog_width-2*border text_height],...
           'String','Okay',...
           'Callback','delete(gcf)');
       
    a_index = a_default;
    b_index = b_default;
       
    % Wait for d to close before running to completion
    uiwait(d);
   
    function popup_callback_x(popup,~)
      a_index = popup.Value;
    end

    function popup_callback_y(popup,~)
      b_index = popup.Value;
    end

end