function [a_index, b_index] = dialog_two_lists(dlg_title, a_title, a_options, b_title, b_options)

    d = dialog('Position',[300 300 460 245],'Name',dlg_title);
    uicontrol('Parent',d,...
           'Style','text',...
           'Position',[20 205 200 25],...
           'String', a_title);
   
    uicontrol('Parent',d,...
           'Style','text',...
           'Position',[240 205 200 25],...
           'String', b_title);
       
    uicontrol('Parent',d,...
           'Style','listbox',...
           'Position',[20 60 200 150],...
           'String', a_options,...
           'Callback',@popup_callback_x);
       
    uicontrol('Parent',d,...
           'Style','listbox',...
           'Position',[240 60 200 150],...
           'String', b_options,...
           'Callback',@popup_callback_y);
       
    uicontrol('Parent',d,...
           'Position',[20 20 420 25],...
           'String','Okay',...
           'Callback','delete(gcf)');
       
    a_index = 1;
    b_index = 1;
       
    % Wait for d to close before running to completion
    uiwait(d);
   
    function popup_callback_x(popup,~)
      a_index = popup.Value;
    end

    function popup_callback_y(popup,~)
      b_index = popup.Value;
    end

end