# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CameraGUIdesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CameraGUI(object):
    def setupUi(self, CameraGUI):
        CameraGUI.setObjectName(_fromUtf8("CameraGUI"))
        CameraGUI.resize(2225, 1296)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CameraGUI.sizePolicy().hasHeightForWidth())
        CameraGUI.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(CameraGUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.ControlsPanel = QtGui.QVBoxLayout(self.layoutWidget)
        self.ControlsPanel.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.ControlsPanel.setObjectName(_fromUtf8("ControlsPanel"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.TakeImagePushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TakeImagePushButton.sizePolicy().hasHeightForWidth())
        self.TakeImagePushButton.setSizePolicy(sizePolicy)
        self.TakeImagePushButton.setObjectName(_fromUtf8("TakeImagePushButton"))
        self.gridLayout.addWidget(self.TakeImagePushButton, 1, 1, 1, 1)
        self.LiveViewCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.LiveViewCheckBox.setObjectName(_fromUtf8("LiveViewCheckBox"))
        self.gridLayout.addWidget(self.LiveViewCheckBox, 1, 0, 1, 1)
        self.OpenCameraPushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenCameraPushButton.sizePolicy().hasHeightForWidth())
        self.OpenCameraPushButton.setSizePolicy(sizePolicy)
        self.OpenCameraPushButton.setObjectName(_fromUtf8("OpenCameraPushButton"))
        self.gridLayout.addWidget(self.OpenCameraPushButton, 0, 0, 1, 1)
        self.CloseCameraPushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseCameraPushButton.sizePolicy().hasHeightForWidth())
        self.CloseCameraPushButton.setSizePolicy(sizePolicy)
        self.CloseCameraPushButton.setObjectName(_fromUtf8("CloseCameraPushButton"))
        self.gridLayout.addWidget(self.CloseCameraPushButton, 0, 1, 1, 1)
        self.AutoExposureCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.AutoExposureCheckBox.setObjectName(_fromUtf8("AutoExposureCheckBox"))
        self.gridLayout.addWidget(self.AutoExposureCheckBox, 2, 0, 1, 1)
        self.SaveImagePushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveImagePushButton.sizePolicy().hasHeightForWidth())
        self.SaveImagePushButton.setSizePolicy(sizePolicy)
        self.SaveImagePushButton.setObjectName(_fromUtf8("SaveImagePushButton"))
        self.gridLayout.addWidget(self.SaveImagePushButton, 2, 1, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.Label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label.sizePolicy().hasHeightForWidth())
        self.Label.setSizePolicy(sizePolicy)
        self.Label.setObjectName(_fromUtf8("Label"))
        self.gridLayout_2.addWidget(self.Label, 0, 0, 1, 1)
        self.Label_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_2.sizePolicy().hasHeightForWidth())
        self.Label_2.setSizePolicy(sizePolicy)
        self.Label_2.setObjectName(_fromUtf8("Label_2"))
        self.gridLayout_2.addWidget(self.Label_2, 1, 0, 1, 1)
        self.FrameRateNumberBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.FrameRateNumberBox.setDecimals(0)
        self.FrameRateNumberBox.setMinimum(1.0)
        self.FrameRateNumberBox.setMaximum(10000.0)
        self.FrameRateNumberBox.setObjectName(_fromUtf8("FrameRateNumberBox"))
        self.gridLayout_2.addWidget(self.FrameRateNumberBox, 1, 1, 1, 1)
        self.ExposureTimeNumberBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.ExposureTimeNumberBox.setDecimals(3)
        self.ExposureTimeNumberBox.setMinimum(0.0)
        self.ExposureTimeNumberBox.setMaximum(10000.0)
        self.ExposureTimeNumberBox.setObjectName(_fromUtf8("ExposureTimeNumberBox"))
        self.gridLayout_2.addWidget(self.ExposureTimeNumberBox, 0, 1, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout_2)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.LiveView = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LiveView.sizePolicy().hasHeightForWidth())
        self.LiveView.setSizePolicy(sizePolicy)
        self.LiveView.setObjectName(_fromUtf8("LiveView"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.LiveView)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.LiveViewWidgetContainer = QtGui.QVBoxLayout()
        self.LiveViewWidgetContainer.setObjectName(_fromUtf8("LiveViewWidgetContainer"))
        self.verticalLayout_3.addLayout(self.LiveViewWidgetContainer)
        self.tabWidget.addTab(self.LiveView, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.splitter)
        CameraGUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(CameraGUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CameraGUI)

    def retranslateUi(self, CameraGUI):
        CameraGUI.setWindowTitle(_translate("CameraGUI", "Camera GUI", None))
        self.TakeImagePushButton.setText(_translate("CameraGUI", "Take Image", None))
        self.LiveViewCheckBox.setText(_translate("CameraGUI", "Live View ", None))
        self.OpenCameraPushButton.setText(_translate("CameraGUI", "Open Camera", None))
        self.CloseCameraPushButton.setText(_translate("CameraGUI", "Close Camera", None))
        self.AutoExposureCheckBox.setText(_translate("CameraGUI", "Auto Exposure ", None))
        self.SaveImagePushButton.setText(_translate("CameraGUI", "Save Image", None))
        self.Label.setText(_translate("CameraGUI", "Exposure time (ms): ", None))
        self.Label_2.setText(_translate("CameraGUI", "Frame rate (fps): ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LiveView), _translate("CameraGUI", "Live View", None))

