# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CameraGUIdesign.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CameraGUI(object):
    def setupUi(self, CameraGUI):
        CameraGUI.setObjectName(_fromUtf8("CameraGUI"))
        CameraGUI.resize(2225, 1296)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CameraGUI.sizePolicy().hasHeightForWidth())
        CameraGUI.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(CameraGUI)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.ControlsPanel = QtGui.QVBoxLayout(self.layoutWidget)
        self.ControlsPanel.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.ControlsPanel.setObjectName(_fromUtf8("ControlsPanel"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.AutoExposureCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.AutoExposureCheckBox.setObjectName(_fromUtf8("AutoExposureCheckBox"))
        self.gridLayout.addWidget(self.AutoExposureCheckBox, 3, 0, 1, 1)
        self.LiveViewCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.LiveViewCheckBox.setObjectName(_fromUtf8("LiveViewCheckBox"))
        self.gridLayout.addWidget(self.LiveViewCheckBox, 2, 0, 1, 1)
        self.TakeImagePushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TakeImagePushButton.sizePolicy().hasHeightForWidth())
        self.TakeImagePushButton.setSizePolicy(sizePolicy)
        self.TakeImagePushButton.setObjectName(_fromUtf8("TakeImagePushButton"))
        self.gridLayout.addWidget(self.TakeImagePushButton, 2, 1, 1, 1)
        self.CloseCameraPushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CloseCameraPushButton.sizePolicy().hasHeightForWidth())
        self.CloseCameraPushButton.setSizePolicy(sizePolicy)
        self.CloseCameraPushButton.setObjectName(_fromUtf8("CloseCameraPushButton"))
        self.gridLayout.addWidget(self.CloseCameraPushButton, 0, 1, 1, 1)
        self.OpenCameraPushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OpenCameraPushButton.sizePolicy().hasHeightForWidth())
        self.OpenCameraPushButton.setSizePolicy(sizePolicy)
        self.OpenCameraPushButton.setObjectName(_fromUtf8("OpenCameraPushButton"))
        self.gridLayout.addWidget(self.OpenCameraPushButton, 0, 0, 1, 1)
        self.SaveImagePushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SaveImagePushButton.sizePolicy().hasHeightForWidth())
        self.SaveImagePushButton.setSizePolicy(sizePolicy)
        self.SaveImagePushButton.setObjectName(_fromUtf8("SaveImagePushButton"))
        self.gridLayout.addWidget(self.SaveImagePushButton, 3, 1, 1, 1)
        self.StartLiveViewPushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StartLiveViewPushButton.sizePolicy().hasHeightForWidth())
        self.StartLiveViewPushButton.setSizePolicy(sizePolicy)
        self.StartLiveViewPushButton.setObjectName(_fromUtf8("StartLiveViewPushButton"))
        self.gridLayout.addWidget(self.StartLiveViewPushButton, 1, 0, 1, 1)
        self.StopLiveViewPushButton = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StopLiveViewPushButton.sizePolicy().hasHeightForWidth())
        self.StopLiveViewPushButton.setSizePolicy(sizePolicy)
        self.StopLiveViewPushButton.setObjectName(_fromUtf8("StopLiveViewPushButton"))
        self.gridLayout.addWidget(self.StopLiveViewPushButton, 1, 1, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout)
        self.line_3 = QtGui.QFrame(self.layoutWidget)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.ControlsPanel.addWidget(self.line_3)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.ExposureTimeNumberBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.ExposureTimeNumberBox.setDecimals(3)
        self.ExposureTimeNumberBox.setMinimum(0.0)
        self.ExposureTimeNumberBox.setMaximum(20.0)
        self.ExposureTimeNumberBox.setSingleStep(0.01)
        self.ExposureTimeNumberBox.setObjectName(_fromUtf8("ExposureTimeNumberBox"))
        self.gridLayout_6.addWidget(self.ExposureTimeNumberBox, 1, 1, 1, 1)
        self.MaxFrameRateLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MaxFrameRateLabel.sizePolicy().hasHeightForWidth())
        self.MaxFrameRateLabel.setSizePolicy(sizePolicy)
        self.MaxFrameRateLabel.setObjectName(_fromUtf8("MaxFrameRateLabel"))
        self.gridLayout_6.addWidget(self.MaxFrameRateLabel, 3, 2, 1, 1)
        self.Label_13 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_13.sizePolicy().hasHeightForWidth())
        self.Label_13.setSizePolicy(sizePolicy)
        self.Label_13.setObjectName(_fromUtf8("Label_13"))
        self.gridLayout_6.addWidget(self.Label_13, 0, 1, 1, 1)
        self.Label_14 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_14.sizePolicy().hasHeightForWidth())
        self.Label_14.setSizePolicy(sizePolicy)
        self.Label_14.setObjectName(_fromUtf8("Label_14"))
        self.gridLayout_6.addWidget(self.Label_14, 0, 2, 1, 1)
        self.Label_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_2.sizePolicy().hasHeightForWidth())
        self.Label_2.setSizePolicy(sizePolicy)
        self.Label_2.setObjectName(_fromUtf8("Label_2"))
        self.gridLayout_6.addWidget(self.Label_2, 3, 0, 1, 1)
        self.Label_4 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_4.sizePolicy().hasHeightForWidth())
        self.Label_4.setSizePolicy(sizePolicy)
        self.Label_4.setObjectName(_fromUtf8("Label_4"))
        self.gridLayout_6.addWidget(self.Label_4, 2, 0, 1, 1)
        self.FramesNumberBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.FramesNumberBox.setDecimals(0)
        self.FramesNumberBox.setMinimum(1.0)
        self.FramesNumberBox.setMaximum(10000.0)
        self.FramesNumberBox.setObjectName(_fromUtf8("FramesNumberBox"))
        self.gridLayout_6.addWidget(self.FramesNumberBox, 2, 1, 1, 1)
        self.CurrentExposureLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentExposureLabel.sizePolicy().hasHeightForWidth())
        self.CurrentExposureLabel.setSizePolicy(sizePolicy)
        self.CurrentExposureLabel.setObjectName(_fromUtf8("CurrentExposureLabel"))
        self.gridLayout_6.addWidget(self.CurrentExposureLabel, 1, 2, 1, 1)
        self.FrameRateNumberBox = QtGui.QSpinBox(self.layoutWidget)
        self.FrameRateNumberBox.setMaximum(9999)
        self.FrameRateNumberBox.setProperty("value", 50)
        self.FrameRateNumberBox.setObjectName(_fromUtf8("FrameRateNumberBox"))
        self.gridLayout_6.addWidget(self.FrameRateNumberBox, 3, 1, 1, 1)
        self.Label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label.sizePolicy().hasHeightForWidth())
        self.Label.setSizePolicy(sizePolicy)
        self.Label.setObjectName(_fromUtf8("Label"))
        self.gridLayout_6.addWidget(self.Label, 1, 0, 1, 1)
        self.Label_3 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_3.sizePolicy().hasHeightForWidth())
        self.Label_3.setSizePolicy(sizePolicy)
        self.Label_3.setObjectName(_fromUtf8("Label_3"))
        self.gridLayout_6.addWidget(self.Label_3, 4, 0, 1, 1)
        self.TimeoutNumberBox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.TimeoutNumberBox.setDecimals(0)
        self.TimeoutNumberBox.setMinimum(0.0)
        self.TimeoutNumberBox.setMaximum(100000.0)
        self.TimeoutNumberBox.setProperty("value", 1000.0)
        self.TimeoutNumberBox.setObjectName(_fromUtf8("TimeoutNumberBox"))
        self.gridLayout_6.addWidget(self.TimeoutNumberBox, 4, 1, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout_6)
        self.line_2 = QtGui.QFrame(self.layoutWidget)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.ControlsPanel.addWidget(self.line_2)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.Label_10 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_10.sizePolicy().hasHeightForWidth())
        self.Label_10.setSizePolicy(sizePolicy)
        self.Label_10.setObjectName(_fromUtf8("Label_10"))
        self.gridLayout_4.addWidget(self.Label_10, 0, 2, 1, 1)
        self.Label_8 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_8.sizePolicy().hasHeightForWidth())
        self.Label_8.setSizePolicy(sizePolicy)
        self.Label_8.setObjectName(_fromUtf8("Label_8"))
        self.gridLayout_4.addWidget(self.Label_8, 2, 0, 1, 1)
        self.MaxHeightLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MaxHeightLabel.sizePolicy().hasHeightForWidth())
        self.MaxHeightLabel.setSizePolicy(sizePolicy)
        self.MaxHeightLabel.setObjectName(_fromUtf8("MaxHeightLabel"))
        self.gridLayout_4.addWidget(self.MaxHeightLabel, 2, 2, 1, 1)
        self.MaxWidthLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MaxWidthLabel.sizePolicy().hasHeightForWidth())
        self.MaxWidthLabel.setSizePolicy(sizePolicy)
        self.MaxWidthLabel.setObjectName(_fromUtf8("MaxWidthLabel"))
        self.gridLayout_4.addWidget(self.MaxWidthLabel, 1, 2, 1, 1)
        self.Label_7 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_7.sizePolicy().hasHeightForWidth())
        self.Label_7.setSizePolicy(sizePolicy)
        self.Label_7.setObjectName(_fromUtf8("Label_7"))
        self.gridLayout_4.addWidget(self.Label_7, 1, 0, 1, 1)
        self.CurrentWidthLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentWidthLabel.sizePolicy().hasHeightForWidth())
        self.CurrentWidthLabel.setSizePolicy(sizePolicy)
        self.CurrentWidthLabel.setObjectName(_fromUtf8("CurrentWidthLabel"))
        self.gridLayout_4.addWidget(self.CurrentWidthLabel, 1, 3, 1, 1)
        self.Label_11 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_11.sizePolicy().hasHeightForWidth())
        self.Label_11.setSizePolicy(sizePolicy)
        self.Label_11.setObjectName(_fromUtf8("Label_11"))
        self.gridLayout_4.addWidget(self.Label_11, 0, 1, 1, 1)
        self.Label_9 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_9.sizePolicy().hasHeightForWidth())
        self.Label_9.setSizePolicy(sizePolicy)
        self.Label_9.setObjectName(_fromUtf8("Label_9"))
        self.gridLayout_4.addWidget(self.Label_9, 0, 3, 1, 1)
        self.CurrentHeightLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CurrentHeightLabel.sizePolicy().hasHeightForWidth())
        self.CurrentHeightLabel.setSizePolicy(sizePolicy)
        self.CurrentHeightLabel.setObjectName(_fromUtf8("CurrentHeightLabel"))
        self.gridLayout_4.addWidget(self.CurrentHeightLabel, 2, 3, 1, 1)
        self.CameraWidthLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CameraWidthLabel.sizePolicy().hasHeightForWidth())
        self.CameraWidthLabel.setSizePolicy(sizePolicy)
        self.CameraWidthLabel.setObjectName(_fromUtf8("CameraWidthLabel"))
        self.gridLayout_4.addWidget(self.CameraWidthLabel, 1, 1, 1, 1)
        self.CameraHeightLabel = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CameraHeightLabel.sizePolicy().hasHeightForWidth())
        self.CameraHeightLabel.setSizePolicy(sizePolicy)
        self.CameraHeightLabel.setObjectName(_fromUtf8("CameraHeightLabel"))
        self.gridLayout_4.addWidget(self.CameraHeightLabel, 2, 1, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout_4)
        self.line = QtGui.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.ControlsPanel.addWidget(self.line)
        self.ROICheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.ROICheckBox.setObjectName(_fromUtf8("ROICheckBox"))
        self.ControlsPanel.addWidget(self.ROICheckBox)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.ROICentreXNumberBox = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROICentreXNumberBox.sizePolicy().hasHeightForWidth())
        self.ROICentreXNumberBox.setSizePolicy(sizePolicy)
        self.ROICentreXNumberBox.setMaximum(9999)
        self.ROICentreXNumberBox.setObjectName(_fromUtf8("ROICentreXNumberBox"))
        self.gridLayout_3.addWidget(self.ROICentreXNumberBox, 8, 1, 1, 1)
        self.ROIWidthNumberBox = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROIWidthNumberBox.sizePolicy().hasHeightForWidth())
        self.ROIWidthNumberBox.setSizePolicy(sizePolicy)
        self.ROIWidthNumberBox.setMaximum(9999)
        self.ROIWidthNumberBox.setObjectName(_fromUtf8("ROIWidthNumberBox"))
        self.gridLayout_3.addWidget(self.ROIWidthNumberBox, 1, 1, 1, 1)
        self.ROIRightEdgeNumberBox = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROIRightEdgeNumberBox.sizePolicy().hasHeightForWidth())
        self.ROIRightEdgeNumberBox.setSizePolicy(sizePolicy)
        self.ROIRightEdgeNumberBox.setMaximum(9999)
        self.ROIRightEdgeNumberBox.setObjectName(_fromUtf8("ROIRightEdgeNumberBox"))
        self.gridLayout_3.addWidget(self.ROIRightEdgeNumberBox, 5, 1, 1, 1)
        self.ROICentreYNumberBox = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROICentreYNumberBox.sizePolicy().hasHeightForWidth())
        self.ROICentreYNumberBox.setSizePolicy(sizePolicy)
        self.ROICentreYNumberBox.setMaximum(9999)
        self.ROICentreYNumberBox.setObjectName(_fromUtf8("ROICentreYNumberBox"))
        self.gridLayout_3.addWidget(self.ROICentreYNumberBox, 9, 1, 1, 1)
        self.ROIRightEdgeCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.ROIRightEdgeCheckBox.setObjectName(_fromUtf8("ROIRightEdgeCheckBox"))
        self.gridLayout_3.addWidget(self.ROIRightEdgeCheckBox, 5, 0, 1, 1)
        self.ROITopEdgeCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.ROITopEdgeCheckBox.setObjectName(_fromUtf8("ROITopEdgeCheckBox"))
        self.gridLayout_3.addWidget(self.ROITopEdgeCheckBox, 6, 0, 1, 1)
        self.ROIBottomEdgeCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.ROIBottomEdgeCheckBox.setObjectName(_fromUtf8("ROIBottomEdgeCheckBox"))
        self.gridLayout_3.addWidget(self.ROIBottomEdgeCheckBox, 7, 0, 1, 1)
        self.ROIBottomEdgeNumberBox = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROIBottomEdgeNumberBox.sizePolicy().hasHeightForWidth())
        self.ROIBottomEdgeNumberBox.setSizePolicy(sizePolicy)
        self.ROIBottomEdgeNumberBox.setMaximum(9999)
        self.ROIBottomEdgeNumberBox.setProperty("value", 0)
        self.ROIBottomEdgeNumberBox.setObjectName(_fromUtf8("ROIBottomEdgeNumberBox"))
        self.gridLayout_3.addWidget(self.ROIBottomEdgeNumberBox, 7, 1, 1, 1)
        self.ROITopEdgeNumberBox = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROITopEdgeNumberBox.sizePolicy().hasHeightForWidth())
        self.ROITopEdgeNumberBox.setSizePolicy(sizePolicy)
        self.ROITopEdgeNumberBox.setMaximum(9999)
        self.ROITopEdgeNumberBox.setProperty("value", 0)
        self.ROITopEdgeNumberBox.setObjectName(_fromUtf8("ROITopEdgeNumberBox"))
        self.gridLayout_3.addWidget(self.ROITopEdgeNumberBox, 6, 1, 1, 1)
        self.ROIHeightNumberBox = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROIHeightNumberBox.sizePolicy().hasHeightForWidth())
        self.ROIHeightNumberBox.setSizePolicy(sizePolicy)
        self.ROIHeightNumberBox.setMaximum(9999)
        self.ROIHeightNumberBox.setObjectName(_fromUtf8("ROIHeightNumberBox"))
        self.gridLayout_3.addWidget(self.ROIHeightNumberBox, 3, 1, 1, 1)
        self.ROIHeightCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.ROIHeightCheckBox.setObjectName(_fromUtf8("ROIHeightCheckBox"))
        self.gridLayout_3.addWidget(self.ROIHeightCheckBox, 3, 0, 1, 1)
        self.ROILeftEdgeNumberBox = QtGui.QSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ROILeftEdgeNumberBox.sizePolicy().hasHeightForWidth())
        self.ROILeftEdgeNumberBox.setSizePolicy(sizePolicy)
        self.ROILeftEdgeNumberBox.setMaximum(9999)
        self.ROILeftEdgeNumberBox.setProperty("value", 0)
        self.ROILeftEdgeNumberBox.setObjectName(_fromUtf8("ROILeftEdgeNumberBox"))
        self.gridLayout_3.addWidget(self.ROILeftEdgeNumberBox, 4, 1, 1, 1)
        self.ROILeftEdgeCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.ROILeftEdgeCheckBox.setObjectName(_fromUtf8("ROILeftEdgeCheckBox"))
        self.gridLayout_3.addWidget(self.ROILeftEdgeCheckBox, 4, 0, 1, 1)
        self.ROIWidthCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.ROIWidthCheckBox.setObjectName(_fromUtf8("ROIWidthCheckBox"))
        self.gridLayout_3.addWidget(self.ROIWidthCheckBox, 1, 0, 1, 1)
        self.ROICentreYCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.ROICentreYCheckBox.setObjectName(_fromUtf8("ROICentreYCheckBox"))
        self.gridLayout_3.addWidget(self.ROICentreYCheckBox, 9, 0, 1, 1)
        self.ROICentreXCheckBox = QtGui.QCheckBox(self.layoutWidget)
        self.ROICentreXCheckBox.setObjectName(_fromUtf8("ROICentreXCheckBox"))
        self.gridLayout_3.addWidget(self.ROICentreXCheckBox, 8, 0, 1, 1)
        self.ControlsPanel.addLayout(self.gridLayout_3)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(1100, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.LiveViewWidget = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LiveViewWidget.sizePolicy().hasHeightForWidth())
        self.LiveViewWidget.setSizePolicy(sizePolicy)
        self.LiveViewWidget.setObjectName(_fromUtf8("LiveViewWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.LiveViewWidget)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.LiveViewWidgetContainer = QtGui.QVBoxLayout()
        self.LiveViewWidgetContainer.setObjectName(_fromUtf8("LiveViewWidgetContainer"))
        self.verticalLayout_3.addLayout(self.LiveViewWidgetContainer)
        self.tabWidget.addTab(self.LiveViewWidget, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.splitter)
        CameraGUI.setCentralWidget(self.centralwidget)

        self.retranslateUi(CameraGUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CameraGUI)

    def retranslateUi(self, CameraGUI):
        CameraGUI.setWindowTitle(_translate("CameraGUI", "Camera GUI", None))
        self.AutoExposureCheckBox.setText(_translate("CameraGUI", "Auto Exposure ", None))
        self.LiveViewCheckBox.setText(_translate("CameraGUI", "Live View ", None))
        self.TakeImagePushButton.setText(_translate("CameraGUI", "Take Image", None))
        self.CloseCameraPushButton.setText(_translate("CameraGUI", "Close Camera", None))
        self.OpenCameraPushButton.setText(_translate("CameraGUI", "Open Camera", None))
        self.SaveImagePushButton.setText(_translate("CameraGUI", "Save Image", None))
        self.StartLiveViewPushButton.setText(_translate("CameraGUI", "Start Live View", None))
        self.StopLiveViewPushButton.setText(_translate("CameraGUI", "Stop Live View", None))
        self.MaxFrameRateLabel.setText(_translate("CameraGUI", "MaxFrameRateLabel", None))
        self.Label_13.setText(_translate("CameraGUI", "Desired", None))
        self.Label_14.setText(_translate("CameraGUI", "Current", None))
        self.Label_2.setText(_translate("CameraGUI", "Frame rate (fps): ", None))
        self.Label_4.setText(_translate("CameraGUI", "Number of frames: ", None))
        self.CurrentExposureLabel.setText(_translate("CameraGUI", "MaxFrameRateLabel", None))
        self.Label.setText(_translate("CameraGUI", "Exposure time (ms): ", None))
        self.Label_3.setText(_translate("CameraGUI", "Timeout (ms):", None))
        self.Label_10.setText(_translate("CameraGUI", "Max avilable", None))
        self.Label_8.setText(_translate("CameraGUI", "Height (px): ", None))
        self.MaxHeightLabel.setText(_translate("CameraGUI", "MaxHeightLabel", None))
        self.MaxWidthLabel.setText(_translate("CameraGUI", "MaxWidthLabel", None))
        self.Label_7.setText(_translate("CameraGUI", "Width (px): ", None))
        self.CurrentWidthLabel.setText(_translate("CameraGUI", "CurrentWidthLabel", None))
        self.Label_11.setText(_translate("CameraGUI", "Total camera", None))
        self.Label_9.setText(_translate("CameraGUI", "Current", None))
        self.CurrentHeightLabel.setText(_translate("CameraGUI", "CurrentHeightLabel", None))
        self.CameraWidthLabel.setText(_translate("CameraGUI", "CameraWidthLabel", None))
        self.CameraHeightLabel.setText(_translate("CameraGUI", "CameraHeightLabel", None))
        self.ROICheckBox.setText(_translate("CameraGUI", "Select Region Of Interest (ROI)", None))
        self.ROIRightEdgeCheckBox.setText(_translate("CameraGUI", "ROI right edge (px): ", None))
        self.ROITopEdgeCheckBox.setText(_translate("CameraGUI", "ROI top edge (px): ", None))
        self.ROIBottomEdgeCheckBox.setText(_translate("CameraGUI", "ROI bottom edge (px): ", None))
        self.ROIHeightCheckBox.setText(_translate("CameraGUI", "ROI height (px): ", None))
        self.ROILeftEdgeCheckBox.setText(_translate("CameraGUI", "ROI left edge (px): ", None))
        self.ROIWidthCheckBox.setText(_translate("CameraGUI", "ROI width (px): ", None))
        self.ROICentreYCheckBox.setText(_translate("CameraGUI", "ROI centre Y (px): ", None))
        self.ROICentreXCheckBox.setText(_translate("CameraGUI", "ROI centre X (px): ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.LiveViewWidget), _translate("CameraGUI", "Live View", None))

