# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testui.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui #,QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(540, 720)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(100, 100))
        MainWindow.setMaximumSize(QtCore.QSize(2000, 2000))
        MainWindow.setWindowOpacity(1.0)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))

        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(30, 30, 480, 600))
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtGui.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")

        self.tabWidgetPage2 = QtGui.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.tabWidgetPage3 = QtGui.QWidget()
        self.tabWidgetPage3.setObjectName("tabWidgetPage3")

        self.verticalLayoutWidget = QtGui.QWidget(self.tabWidgetPage1)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 35, 400, 520))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.horpl_12 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_12.sizePolicy().hasHeightForWidth())
        self.horpl_12.setSizePolicy(sizePolicy)
        self.horpl_12.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_12.setObjectName(_fromUtf8("horpl_12"))
        self.horizontalLayout_12.addWidget(self.horpl_12)
        self.horv = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horv.sizePolicy().hasHeightForWidth())
        self.horv.setSizePolicy(sizePolicy)
        self.horv.setMaximumSize(QtCore.QSize(70, 16777215))
        self.horv.setObjectName(_fromUtf8("horv"))
        self.horizontalLayout_12.addWidget(self.horv, QtCore.Qt.AlignHCenter)
        self.horpl_18 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_18.sizePolicy().hasHeightForWidth())
        self.horpl_18.setSizePolicy(sizePolicy)
        self.horpl_18.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_18.setText(_fromUtf8(""))
        self.horpl_18.setObjectName(_fromUtf8("horpl_18"))
        self.horizontalLayout_12.addWidget(self.horpl_18)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.horposi = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horposi.sizePolicy().hasHeightForWidth())
        self.horposi.setSizePolicy(sizePolicy)
        self.horposi.setMaximumSize(QtCore.QSize(50, 16777215))
        self.horposi.setObjectName(_fromUtf8("horposi"))
        self.horizontalLayout.addWidget(self.horposi)
        self.horposs = QtGui.QSlider(self.verticalLayoutWidget)
        self.horposs.setSliderPosition(50)
        self.horposs.setTracking(False)
        self.horposs.setOrientation(QtCore.Qt.Horizontal)
        self.horposs.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horposs.setTickInterval(1)
        self.horposs.setObjectName(_fromUtf8("horposs"))
        self.horizontalLayout.addWidget(self.horposs)
        self.horposa = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horposa.sizePolicy().hasHeightForWidth())
        self.horposa.setSizePolicy(sizePolicy)
        self.horposa.setMaximumSize(QtCore.QSize(50, 16777215))
        self.horposa.setObjectName(_fromUtf8("horposa"))
        self.horizontalLayout.addWidget(self.horposa)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.horpl_8 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_8.sizePolicy().hasHeightForWidth())
        self.horpl_8.setSizePolicy(sizePolicy)
        self.horpl_8.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_8.setObjectName(_fromUtf8("horpl_8"))
        self.horizontalLayout_7.addWidget(self.horpl_8)
        self.hora = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hora.sizePolicy().hasHeightForWidth())
        self.hora.setSizePolicy(sizePolicy)
        self.hora.setMaximumSize(QtCore.QSize(70, 16777215))
        self.hora.setObjectName(_fromUtf8("hora"))
        self.horizontalLayout_7.addWidget(self.hora, QtCore.Qt.AlignHCenter)
        self.horpl_13 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_13.sizePolicy().hasHeightForWidth())
        self.horpl_13.setSizePolicy(sizePolicy)
        self.horpl_13.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_13.setText(_fromUtf8(""))
        self.horpl_13.setObjectName(_fromUtf8("horpl_13"))
        self.horizontalLayout_7.addWidget(self.horpl_13)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.horangi = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horangi.sizePolicy().hasHeightForWidth())
        self.horangi.setSizePolicy(sizePolicy)
        self.horangi.setMaximumSize(QtCore.QSize(50, 16777215))
        self.horangi.setObjectName(_fromUtf8("horangi"))
        self.horizontalLayout_2.addWidget(self.horangi)
        self.horangs = QtGui.QSlider(self.verticalLayoutWidget)
        self.horangs.setSliderPosition(50)
        self.horangs.setTracking(False)
        self.horangs.setOrientation(QtCore.Qt.Horizontal)
        self.horangs.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horangs.setTickInterval(1)
        self.horangs.setObjectName(_fromUtf8("horangs"))
        self.horizontalLayout_2.addWidget(self.horangs)
        self.horanga = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horanga.sizePolicy().hasHeightForWidth())
        self.horanga.setSizePolicy(sizePolicy)
        self.horanga.setMinimumSize(QtCore.QSize(0, 0))
        self.horanga.setMaximumSize(QtCore.QSize(50, 16777215))
        self.horanga.setObjectName(_fromUtf8("horanga"))
        self.horizontalLayout_2.addWidget(self.horanga)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horpl_9 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_9.sizePolicy().hasHeightForWidth())
        self.horpl_9.setSizePolicy(sizePolicy)
        self.horpl_9.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_9.setObjectName(_fromUtf8("horpl_9"))
        self.horizontalLayout_8.addWidget(self.horpl_9)
        self.verv = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verv.sizePolicy().hasHeightForWidth())
        self.verv.setSizePolicy(sizePolicy)
        self.verv.setMaximumSize(QtCore.QSize(70, 16777215))
        self.verv.setObjectName(_fromUtf8("verv"))
        self.horizontalLayout_8.addWidget(self.verv, QtCore.Qt.AlignHCenter)
        self.horpl_14 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_14.sizePolicy().hasHeightForWidth())
        self.horpl_14.setSizePolicy(sizePolicy)
        self.horpl_14.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_14.setText(_fromUtf8(""))
        self.horpl_14.setObjectName(_fromUtf8("horpl_14"))
        self.horizontalLayout_8.addWidget(self.horpl_14)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verposi = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verposi.sizePolicy().hasHeightForWidth())
        self.verposi.setSizePolicy(sizePolicy)
        self.verposi.setMaximumSize(QtCore.QSize(50, 16777215))
        self.verposi.setObjectName(_fromUtf8("verposi"))
        self.horizontalLayout_3.addWidget(self.verposi)
        self.verposs = QtGui.QSlider(self.verticalLayoutWidget)
        self.verposs.setSliderPosition(50)
        self.verposs.setTracking(False)
        self.verposs.setOrientation(QtCore.Qt.Horizontal)
        self.verposs.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verposs.setTickInterval(1)
        self.verposs.setObjectName(_fromUtf8("verposs"))
        self.horizontalLayout_3.addWidget(self.verposs)
        self.verposa = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verposa.sizePolicy().hasHeightForWidth())
        self.verposa.setSizePolicy(sizePolicy)
        self.verposa.setMinimumSize(QtCore.QSize(0, 0))
        self.verposa.setMaximumSize(QtCore.QSize(50, 16777215))
        self.verposa.setObjectName(_fromUtf8("verposa"))
        self.horizontalLayout_3.addWidget(self.verposa)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.horpl_10 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_10.sizePolicy().hasHeightForWidth())
        self.horpl_10.setSizePolicy(sizePolicy)
        self.horpl_10.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_10.setObjectName(_fromUtf8("horpl_10"))
        self.horizontalLayout_9.addWidget(self.horpl_10)
        self.vera = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vera.sizePolicy().hasHeightForWidth())
        self.vera.setSizePolicy(sizePolicy)
        self.vera.setMaximumSize(QtCore.QSize(70, 16777215))
        self.vera.setObjectName(_fromUtf8("vera"))
        self.horizontalLayout_9.addWidget(self.vera, QtCore.Qt.AlignHCenter)
        self.horpl_15 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_15.sizePolicy().hasHeightForWidth())
        self.horpl_15.setSizePolicy(sizePolicy)
        self.horpl_15.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_15.setText(_fromUtf8(""))
        self.horpl_15.setObjectName(_fromUtf8("horpl_15"))
        self.horizontalLayout_9.addWidget(self.horpl_15)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verangi = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verangi.sizePolicy().hasHeightForWidth())
        self.verangi.setSizePolicy(sizePolicy)
        self.verangi.setMaximumSize(QtCore.QSize(50, 16777215))
        self.verangi.setObjectName(_fromUtf8("verangi"))
        self.horizontalLayout_4.addWidget(self.verangi)
        self.verangs = QtGui.QSlider(self.verticalLayoutWidget)
        self.verangs.setSliderPosition(50)
        self.verangs.setTracking(False)
        self.verangs.setOrientation(QtCore.Qt.Horizontal)
        self.verangs.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verangs.setTickInterval(1)
        self.verangs.setObjectName(_fromUtf8("verangs"))
        self.horizontalLayout_4.addWidget(self.verangs)
        self.veranga = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.veranga.sizePolicy().hasHeightForWidth())
        self.veranga.setSizePolicy(sizePolicy)
        self.veranga.setMinimumSize(QtCore.QSize(0, 0))
        self.veranga.setMaximumSize(QtCore.QSize(50, 16777215))
        self.veranga.setObjectName(_fromUtf8("veranga"))
        self.horizontalLayout_4.addWidget(self.veranga)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.horpl_11 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_11.sizePolicy().hasHeightForWidth())
        self.horpl_11.setSizePolicy(sizePolicy)
        self.horpl_11.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_11.setObjectName(_fromUtf8("horpl_11"))
        self.horizontalLayout_10.addWidget(self.horpl_11)
        self.sv = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sv.sizePolicy().hasHeightForWidth())
        self.sv.setSizePolicy(sizePolicy)
        self.sv.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sv.setObjectName(_fromUtf8("sv"))
        self.horizontalLayout_10.addWidget(self.sv, QtCore.Qt.AlignHCenter)
        self.horpl_16 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_16.sizePolicy().hasHeightForWidth())
        self.horpl_16.setSizePolicy(sizePolicy)
        self.horpl_16.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_16.setText(_fromUtf8(""))
        self.horpl_16.setObjectName(_fromUtf8("horpl_16"))
        self.horizontalLayout_10.addWidget(self.horpl_16)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.sizei = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizei.sizePolicy().hasHeightForWidth())
        self.sizei.setSizePolicy(sizePolicy)
        self.sizei.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sizei.setObjectName(_fromUtf8("sizei"))
        self.horizontalLayout_5.addWidget(self.sizei)
        self.sizes = QtGui.QSlider(self.verticalLayoutWidget)
        self.sizes.setSliderPosition(50)
        self.sizes.setTracking(False)
        self.sizes.setOrientation(QtCore.Qt.Horizontal)
        self.sizes.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sizes.setTickInterval(1)
        self.sizes.setObjectName(_fromUtf8("sizes"))
        self.horizontalLayout_5.addWidget(self.sizes)
        self.sizea = QtGui.QLineEdit(self.verticalLayoutWidget)

        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizea.sizePolicy().hasHeightForWidth())
        self.sizea.setSizePolicy(sizePolicy)
        self.sizea.setMinimumSize(QtCore.QSize(0, 0))
        self.sizea.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sizea.setObjectName(_fromUtf8("sizea"))
        self.horizontalLayout_5.addWidget(self.sizea)
        self.verticalLayout.addLayout(self.horizontalLayout_5)

        spacerItem7 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.horpl_20 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_20.sizePolicy().hasHeightForWidth())
        self.horpl_20.setSizePolicy(sizePolicy)
        self.horpl_20.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_20.setObjectName(_fromUtf8("horpl_20"))
        self.horizontalLayout_20.addWidget(self.horpl_20)
        self.fv = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fv.sizePolicy().hasHeightForWidth())
        self.fv.setSizePolicy(sizePolicy)
        self.fv.setMaximumSize(QtCore.QSize(70, 16777215))
        self.fv.setObjectName(_fromUtf8("fv"))
        self.horizontalLayout_20.addWidget(self.fv, QtCore.Qt.AlignHCenter)
        self.horpl_21 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_21.sizePolicy().hasHeightForWidth())
        self.horpl_21.setSizePolicy(sizePolicy)
        self.horpl_21.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_21.setText(_fromUtf8(""))
        self.horpl_21.setObjectName(_fromUtf8("horpl_21"))
        self.horizontalLayout_20.addWidget(self.horpl_21)
        self.verticalLayout.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.focusi = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.focusi.sizePolicy().hasHeightForWidth())
        self.focusi.setSizePolicy(sizePolicy)
        self.focusi.setMaximumSize(QtCore.QSize(50, 16777215))
        self.focusi.setObjectName(_fromUtf8("focusi"))
        self.horizontalLayout_21.addWidget(self.focusi)
        self.focuss = QtGui.QSlider(self.verticalLayoutWidget)
        self.focuss.setSliderPosition(50)
        self.focuss.setTracking(False)
        self.focuss.setOrientation(QtCore.Qt.Horizontal)
        self.focuss.setTickPosition(QtGui.QSlider.TicksBelow)
        self.focuss.setTickInterval(1)
        self.focuss.setObjectName(_fromUtf8("focuss"))
        self.horizontalLayout_21.addWidget(self.focuss)
        self.focusa = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.focusa.sizePolicy().hasHeightForWidth())
        self.focusa.setSizePolicy(sizePolicy)
        self.focusa.setMinimumSize(QtCore.QSize(0, 0))
        self.focusa.setMaximumSize(QtCore.QSize(50, 16777215))
        self.focusa.setObjectName(_fromUtf8("focusa"))
        self.horizontalLayout_21.addWidget(self.focusa)
        self.verticalLayout.addLayout(self.horizontalLayout_21)


        spacerItem4 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_7.addWidget(self.label_2)
        self.lbox = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.lbox.setObjectName(_fromUtf8("lbox"))
        self.verticalLayout_7.addWidget(self.lbox)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.horizontalLayout_18.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_8.addWidget(self.label_3)
        self.gbox = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.gbox.setObjectName(_fromUtf8("gbox"))
        self.verticalLayout_8.addWidget(self.gbox)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem6)
        self.horizontalLayout_18.addLayout(self.verticalLayout_8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)

        self.updateb = QtGui.QPushButton(self.verticalLayoutWidget)
        self.updateb.setObjectName("updateb")
        self.verticalLayout_6.addWidget(self.updateb)

        self.horizontalLayout_19.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.horpl_6 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_6.sizePolicy().hasHeightForWidth())
        self.horpl_6.setSizePolicy(sizePolicy)
        self.horpl_6.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_6.setObjectName(_fromUtf8("horpl_6"))
        self.horizontalLayout_11.addWidget(self.horpl_6)
        self.rv = QtGui.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rv.sizePolicy().hasHeightForWidth())
        self.rv.setSizePolicy(sizePolicy)
        self.rv.setMaximumSize(QtCore.QSize(70, 16777215))
        self.rv.setObjectName(_fromUtf8("rv"))
        self.horizontalLayout_11.addWidget(self.rv, QtCore.Qt.AlignHCenter)
        self.horpl_17 = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_17.sizePolicy().hasHeightForWidth())
        self.horpl_17.setSizePolicy(sizePolicy)
        self.horpl_17.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_17.setText(_fromUtf8(""))
        self.horpl_17.setObjectName(_fromUtf8("horpl_17"))
        self.horizontalLayout_11.addWidget(self.horpl_17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.dial = QtGui.QDial(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial.sizePolicy().hasHeightForWidth())
        self.dial.setSizePolicy(sizePolicy)
        self.dial.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.dial.setMaximum(360)
        self.dial.setProperty("value", 0)
        self.dial.setTracking(False)
        self.dial.setOrientation(QtCore.Qt.Vertical)
        self.dial.setWrapping(True)
        self.dial.setNotchTarget(5.0)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName(_fromUtf8("dial"))
        self.verticalLayout_3.addWidget(self.dial)
        self.horizontalLayout_19.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.verticalLayoutWidget_b = QtGui.QWidget(self.tabWidgetPage2)
        self.verticalLayoutWidget_b.setGeometry(QtCore.QRect(40, 35, 400, 520))
        self.verticalLayoutWidget_b.setObjectName(_fromUtf8("verticalLayoutWidget_b"))
        self.verticalLayout_b = QtGui.QVBoxLayout(self.verticalLayoutWidget_b)
        self.verticalLayout_b.setObjectName(_fromUtf8("verticalLayout_b"))
        self.horizontalLayout_b_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_12.setObjectName(_fromUtf8("horizontalLayout_b_12"))
        self.horpl_b_12 = QtGui.QLabel(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_b_12.sizePolicy().hasHeightForWidth())
        self.horpl_b_12.setSizePolicy(sizePolicy)
        self.horpl_b_12.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_b_12.setObjectName(_fromUtf8("horpl_b_12"))
        self.horizontalLayout_b_12.addWidget(self.horpl_b_12)
        self.horv_b = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horv_b.sizePolicy().hasHeightForWidth())
        self.horv_b.setSizePolicy(sizePolicy)
        self.horv_b.setMaximumSize(QtCore.QSize(70, 16777215))
        self.horv_b.setObjectName(_fromUtf8("horv_b"))
        self.horizontalLayout_b_12.addWidget(self.horv_b, QtCore.Qt.AlignHCenter)
        self.horpl_b_18 = QtGui.QLabel(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_b_18.sizePolicy().hasHeightForWidth())
        self.horpl_b_18.setSizePolicy(sizePolicy)
        self.horpl_b_18.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_b_18.setText(_fromUtf8(""))
        self.horpl_b_18.setObjectName(_fromUtf8("horpl_b_18"))
        self.horizontalLayout_b_12.addWidget(self.horpl_b_18)
        self.verticalLayout_b.addLayout(self.horizontalLayout_b_12)
        self.horizontalLayout_b = QtGui.QHBoxLayout()
        self.horizontalLayout_b.setObjectName(_fromUtf8("horizontalLayout_b"))
        self.horpos_b_i = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpos_b_i.sizePolicy().hasHeightForWidth())
        self.horpos_b_i.setSizePolicy(sizePolicy)
        self.horpos_b_i.setMaximumSize(QtCore.QSize(50, 16777215))
        self.horpos_b_i.setObjectName(_fromUtf8("horpos_b_i"))
        self.horizontalLayout_b.addWidget(self.horpos_b_i)
        self.horpos_b_s = QtGui.QSlider(self.verticalLayoutWidget_b)
        self.horpos_b_s.setSliderPosition(50)
        self.horpos_b_s.setTracking(False)
        self.horpos_b_s.setOrientation(QtCore.Qt.Horizontal)
        self.horpos_b_s.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horpos_b_s.setTickInterval(1)
        self.horpos_b_s.setObjectName(_fromUtf8("horpos_b_s"))
        self.horizontalLayout_b.addWidget(self.horpos_b_s)
        self.horpos_b_a = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpos_b_a.sizePolicy().hasHeightForWidth())
        self.horpos_b_a.setSizePolicy(sizePolicy)
        self.horpos_b_a.setMaximumSize(QtCore.QSize(50, 16777215))
        self.horpos_b_a.setObjectName(_fromUtf8("horpos_b_a"))
        self.horizontalLayout_b.addWidget(self.horpos_b_a)
        self.verticalLayout_b.addLayout(self.horizontalLayout_b)
        spacerItem_b = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_b.addItem(spacerItem_b)
        self.horizontalLayout_b_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_7.setObjectName(_fromUtf8("horizontalLayout_b_7"))
        self.horpl_b_8 = QtGui.QLabel(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_b_8.sizePolicy().hasHeightForWidth())
        self.horpl_b_8.setSizePolicy(sizePolicy)
        self.horpl_b_8.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_b_8.setObjectName(_fromUtf8("horpl_b_8"))
        self.horizontalLayout_b_7.addWidget(self.horpl_b_8)
        self.hora_b = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hora_b.sizePolicy().hasHeightForWidth())
        self.hora_b.setSizePolicy(sizePolicy)
        self.hora_b.setMaximumSize(QtCore.QSize(70, 16777215))
        self.hora_b.setObjectName(_fromUtf8("hora_b"))
        self.horizontalLayout_b_7.addWidget(self.hora_b, QtCore.Qt.AlignHCenter)
        self.horpl_b_13 = QtGui.QLabel(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_b_13.sizePolicy().hasHeightForWidth())
        self.horpl_b_13.setSizePolicy(sizePolicy)
        self.horpl_b_13.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_b_13.setText(_fromUtf8(""))
        self.horpl_b_13.setObjectName(_fromUtf8("horpl_b_13"))
        self.horizontalLayout_b_7.addWidget(self.horpl_b_13)
        self.verticalLayout_b.addLayout(self.horizontalLayout_b_7)
        self.horizontalLayout_b_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_2.setObjectName(_fromUtf8("horizontalLayout_b_2"))
        self.horang_b_i = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horang_b_i.sizePolicy().hasHeightForWidth())
        self.horang_b_i.setSizePolicy(sizePolicy)
        self.horang_b_i.setMaximumSize(QtCore.QSize(50, 16777215))
        self.horang_b_i.setObjectName(_fromUtf8("horang_b_i"))
        self.horizontalLayout_b_2.addWidget(self.horang_b_i)
        self.horang_b_s = QtGui.QSlider(self.verticalLayoutWidget_b)
        self.horang_b_s.setSliderPosition(50)
        self.horang_b_s.setTracking(False)
        self.horang_b_s.setOrientation(QtCore.Qt.Horizontal)
        self.horang_b_s.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horang_b_s.setTickInterval(1)
        self.horang_b_s.setObjectName(_fromUtf8("horang_b_s"))
        self.horizontalLayout_b_2.addWidget(self.horang_b_s)
        self.horang_b_a = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horang_b_a.sizePolicy().hasHeightForWidth())
        self.horang_b_a.setSizePolicy(sizePolicy)
        self.horang_b_a.setMinimumSize(QtCore.QSize(0, 0))
        self.horang_b_a.setMaximumSize(QtCore.QSize(50, 16777215))
        self.horang_b_a.setObjectName(_fromUtf8("horang_b_a"))
        self.horizontalLayout_b_2.addWidget(self.horang_b_a)
        self.verticalLayout_b.addLayout(self.horizontalLayout_b_2)
        spacerItem_b1 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_b.addItem(spacerItem_b1)
        self.horizontalLayout_b_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_8.setObjectName(_fromUtf8("horizontalLayout_b_8"))
        self.horpl_b_9 = QtGui.QLabel(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_b_9.sizePolicy().hasHeightForWidth())
        self.horpl_b_9.setSizePolicy(sizePolicy)
        self.horpl_b_9.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_b_9.setObjectName(_fromUtf8("horpl_b_9"))
        self.horizontalLayout_b_8.addWidget(self.horpl_b_9)
        self.verv_b = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verv_b.sizePolicy().hasHeightForWidth())
        self.verv_b.setSizePolicy(sizePolicy)
        self.verv_b.setMaximumSize(QtCore.QSize(70, 16777215))
        self.verv_b.setObjectName(_fromUtf8("verv_b"))
        self.horizontalLayout_b_8.addWidget(self.verv_b, QtCore.Qt.AlignHCenter)
        self.horpl_b_14 = QtGui.QLabel(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_b_14.sizePolicy().hasHeightForWidth())
        self.horpl_b_14.setSizePolicy(sizePolicy)
        self.horpl_b_14.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_b_14.setText(_fromUtf8(""))
        self.horpl_b_14.setObjectName(_fromUtf8("horpl_b_14"))
        self.horizontalLayout_b_8.addWidget(self.horpl_b_14)
        self.verticalLayout_b.addLayout(self.horizontalLayout_b_8)
        self.horizontalLayout_b_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_3.setObjectName(_fromUtf8("horizontalLayout_b_3"))
        self.verpos_b_i = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verpos_b_i.sizePolicy().hasHeightForWidth())
        self.verpos_b_i.setSizePolicy(sizePolicy)
        self.verpos_b_i.setMaximumSize(QtCore.QSize(50, 16777215))
        self.verpos_b_i.setObjectName(_fromUtf8("verpos_b_i"))
        self.horizontalLayout_b_3.addWidget(self.verpos_b_i)
        self.verpos_b_s = QtGui.QSlider(self.verticalLayoutWidget_b)
        self.verpos_b_s.setSliderPosition(50)
        self.verpos_b_s.setTracking(False)
        self.verpos_b_s.setOrientation(QtCore.Qt.Horizontal)
        self.verpos_b_s.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verpos_b_s.setTickInterval(1)
        self.verpos_b_s.setObjectName(_fromUtf8("verpos_b_s"))
        self.horizontalLayout_b_3.addWidget(self.verpos_b_s)
        self.verpos_b_a = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verpos_b_a.sizePolicy().hasHeightForWidth())
        self.verpos_b_a.setSizePolicy(sizePolicy)
        self.verpos_b_a.setMinimumSize(QtCore.QSize(0, 0))
        self.verpos_b_a.setMaximumSize(QtCore.QSize(50, 16777215))
        self.verpos_b_a.setObjectName(_fromUtf8("verpos_b_a"))
        self.horizontalLayout_b_3.addWidget(self.verpos_b_a)
        self.verticalLayout_b.addLayout(self.horizontalLayout_b_3)
        spacerItem_b2 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_b.addItem(spacerItem_b2)
        self.horizontalLayout_b_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_9.setObjectName(_fromUtf8("horizontalLayout_b_9"))
        self.horpl_b_10 = QtGui.QLabel(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_b_10.sizePolicy().hasHeightForWidth())
        self.horpl_b_10.setSizePolicy(sizePolicy)
        self.horpl_b_10.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_b_10.setObjectName(_fromUtf8("horpl_b_10"))
        self.horizontalLayout_b_9.addWidget(self.horpl_b_10)
        self.vera_b = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vera_b.sizePolicy().hasHeightForWidth())
        self.vera_b.setSizePolicy(sizePolicy)
        self.vera_b.setMaximumSize(QtCore.QSize(70, 16777215))
        self.vera_b.setObjectName(_fromUtf8("vera_b"))
        self.horizontalLayout_b_9.addWidget(self.vera_b, QtCore.Qt.AlignHCenter)
        self.horpl_b_15 = QtGui.QLabel(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_b_15.sizePolicy().hasHeightForWidth())
        self.horpl_b_15.setSizePolicy(sizePolicy)
        self.horpl_b_15.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_b_15.setText(_fromUtf8(""))
        self.horpl_b_15.setObjectName(_fromUtf8("horpl_b_15"))
        self.horizontalLayout_b_9.addWidget(self.horpl_b_15)
        self.verticalLayout_b.addLayout(self.horizontalLayout_b_9)
        self.horizontalLayout_b_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_4.setObjectName(_fromUtf8("horizontalLayout_b_4"))
        self.verang_b_i = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verang_b_i.sizePolicy().hasHeightForWidth())
        self.verang_b_i.setSizePolicy(sizePolicy)
        self.verang_b_i.setMaximumSize(QtCore.QSize(50, 16777215))
        self.verang_b_i.setObjectName(_fromUtf8("verang_b_i"))
        self.horizontalLayout_b_4.addWidget(self.verang_b_i)
        self.verang_b_s = QtGui.QSlider(self.verticalLayoutWidget_b)
        self.verang_b_s.setSliderPosition(50)
        self.verang_b_s.setTracking(False)
        self.verang_b_s.setOrientation(QtCore.Qt.Horizontal)
        self.verang_b_s.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verang_b_s.setTickInterval(1)
        self.verang_b_s.setObjectName(_fromUtf8("verang_b_s"))
        self.horizontalLayout_b_4.addWidget(self.verang_b_s)
        self.verang_b_a = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verang_b_a.sizePolicy().hasHeightForWidth())
        self.verang_b_a.setSizePolicy(sizePolicy)
        self.verang_b_a.setMinimumSize(QtCore.QSize(0, 0))
        self.verang_b_a.setMaximumSize(QtCore.QSize(50, 16777215))
        self.verang_b_a.setObjectName(_fromUtf8("verang_b_a"))
        self.horizontalLayout_b_4.addWidget(self.verang_b_a)
        self.verticalLayout_b.addLayout(self.horizontalLayout_b_4)
        spacerItem_b3 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_b.addItem(spacerItem_b3)
        self.horizontalLayout_b_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_10.setObjectName(_fromUtf8("horizontalLayout_b_10"))
        self.horpl_b_11 = QtGui.QLabel(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_b_11.sizePolicy().hasHeightForWidth())
        self.horpl_b_11.setSizePolicy(sizePolicy)
        self.horpl_b_11.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_b_11.setObjectName(_fromUtf8("horpl_b_11"))
        self.horizontalLayout_b_10.addWidget(self.horpl_b_11)
        self.sv_b = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sv_b.sizePolicy().hasHeightForWidth())
        self.sv_b.setSizePolicy(sizePolicy)
        self.sv_b.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sv_b.setObjectName(_fromUtf8("sv_b"))
        self.horizontalLayout_b_10.addWidget(self.sv_b, QtCore.Qt.AlignHCenter)
        self.horpl_b_16 = QtGui.QLabel(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_b_16.sizePolicy().hasHeightForWidth())
        self.horpl_b_16.setSizePolicy(sizePolicy)
        self.horpl_b_16.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_b_16.setText(_fromUtf8(""))
        self.horpl_b_16.setObjectName(_fromUtf8("horpl_b_16"))
        self.horizontalLayout_b_10.addWidget(self.horpl_b_16)
        self.verticalLayout_b.addLayout(self.horizontalLayout_b_10)
        self.horizontalLayout_b_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_5.setObjectName(_fromUtf8("horizontalLayout_b_5"))
        self.sizei_b = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizei_b.sizePolicy().hasHeightForWidth())
        self.sizei_b.setSizePolicy(sizePolicy)
        self.sizei_b.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sizei_b.setObjectName(_fromUtf8("sizei_b"))
        self.horizontalLayout_b_5.addWidget(self.sizei_b)
        self.sizes_b = QtGui.QSlider(self.verticalLayoutWidget_b)
        self.sizes_b.setSliderPosition(50)
        self.sizes_b.setTracking(False)
        self.sizes_b.setOrientation(QtCore.Qt.Horizontal)
        self.sizes_b.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sizes_b.setTickInterval(1)
        self.sizes_b.setObjectName(_fromUtf8("sizes_b"))
        self.horizontalLayout_b_5.addWidget(self.sizes_b)
        self.sizea_b = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizea_b.sizePolicy().hasHeightForWidth())
        self.sizea_b.setSizePolicy(sizePolicy)
        self.sizea_b.setMinimumSize(QtCore.QSize(0, 0))
        self.sizea_b.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sizea_b.setObjectName(_fromUtf8("sizea_b"))
        self.horizontalLayout_b_5.addWidget(self.sizea_b)
        self.verticalLayout_b.addLayout(self.horizontalLayout_b_5)

        spacerItem_b7 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_b.addItem(spacerItem_b7)
        self.horizontalLayout_b_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_20.setObjectName(_fromUtf8("horizontalLayout_b_20"))
        self.horpl_b_20 = QtGui.QLabel(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_b_20.sizePolicy().hasHeightForWidth())
        self.horpl_b_20.setSizePolicy(sizePolicy)
        self.horpl_b_20.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_b_20.setObjectName(_fromUtf8("horpl_b_20"))
        self.horizontalLayout_b_20.addWidget(self.horpl_b_20)
        self.fv_b = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fv_b.sizePolicy().hasHeightForWidth())
        self.fv_b.setSizePolicy(sizePolicy)
        self.fv_b.setMaximumSize(QtCore.QSize(70, 16777215))
        self.fv_b.setObjectName(_fromUtf8("fv_b"))
        self.horizontalLayout_b_20.addWidget(self.fv_b, QtCore.Qt.AlignHCenter)
        self.horpl_b_21 = QtGui.QLabel(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_b_21.sizePolicy().hasHeightForWidth())
        self.horpl_b_21.setSizePolicy(sizePolicy)
        self.horpl_b_21.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_b_21.setText(_fromUtf8(""))
        self.horpl_b_21.setObjectName(_fromUtf8("horpl_b_21"))
        self.horizontalLayout_b_20.addWidget(self.horpl_b_21)
        self.verticalLayout_b.addLayout(self.horizontalLayout_b_20)
        self.horizontalLayout_b_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_21.setObjectName(_fromUtf8("horizontalLayout_b_21"))
        self.focus_b_i = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.focus_b_i.sizePolicy().hasHeightForWidth())
        self.focus_b_i.setSizePolicy(sizePolicy)
        self.focus_b_i.setMaximumSize(QtCore.QSize(50, 16777215))
        self.focus_b_i.setObjectName(_fromUtf8("focus_b_i"))
        self.horizontalLayout_b_21.addWidget(self.focus_b_i)
        self.focus_b_s = QtGui.QSlider(self.verticalLayoutWidget_b)
        self.focus_b_s.setSliderPosition(50)
        self.focus_b_s.setTracking(False)
        self.focus_b_s.setOrientation(QtCore.Qt.Horizontal)
        self.focus_b_s.setTickPosition(QtGui.QSlider.TicksBelow)
        self.focus_b_s.setTickInterval(1)
        self.focus_b_s.setObjectName(_fromUtf8("focus_b_s"))
        self.horizontalLayout_b_21.addWidget(self.focus_b_s)
        self.focus_b_a = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.focus_b_a.sizePolicy().hasHeightForWidth())
        self.focus_b_a.setSizePolicy(sizePolicy)
        self.focus_b_a.setMinimumSize(QtCore.QSize(0, 0))
        self.focus_b_a.setMaximumSize(QtCore.QSize(50, 16777215))
        self.focus_b_a.setObjectName(_fromUtf8("focus_b_a"))
        self.horizontalLayout_b_21.addWidget(self.focus_b_a)
        self.verticalLayout_b.addLayout(self.horizontalLayout_b_21)

        spacerItem_b4 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_b.addItem(spacerItem_b4)
        self.horizontalLayout_b_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_19.setObjectName(_fromUtf8("horizontalLayout_b_19"))
        self.verticalLayout_b_6 = QtGui.QVBoxLayout()
        self.verticalLayout_b_6.setObjectName(_fromUtf8("verticalLayout_b_6"))
        self.horizontalLayout_b_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_18.setObjectName(_fromUtf8("horizontalLayout_b_18"))
        self.verticalLayout_b_7 = QtGui.QVBoxLayout()
        self.verticalLayout_b_7.setObjectName(_fromUtf8("verticalLayout_b_7"))
        self.label_2_b = QtGui.QLabel(self.verticalLayoutWidget_b)
        self.label_2_b.setObjectName(_fromUtf8("label_2_b"))
        self.verticalLayout_b_7.addWidget(self.label_2_b)
        self.lbox_b = QtGui.QSpinBox(self.verticalLayoutWidget_b)
        self.lbox_b.setObjectName(_fromUtf8("lbox_b"))
        self.verticalLayout_b_7.addWidget(self.lbox_b)
        spacerItem_b5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_b_7.addItem(spacerItem_b5)
        self.horizontalLayout_b_18.addLayout(self.verticalLayout_b_7)
        self.verticalLayout_b_8 = QtGui.QVBoxLayout()
        self.verticalLayout_b_8.setObjectName(_fromUtf8("verticalLayout_b_8"))
        self.label_3_b = QtGui.QLabel(self.verticalLayoutWidget_b)
        self.label_3_b.setObjectName(_fromUtf8("label_3_b"))
        self.verticalLayout_b_8.addWidget(self.label_3_b)
        self.gbox_b = QtGui.QSpinBox(self.verticalLayoutWidget_b)
        self.gbox_b.setObjectName(_fromUtf8("gbox_b"))
        self.verticalLayout_b_8.addWidget(self.gbox_b)
        spacerItem_b6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_b_8.addItem(spacerItem_b6)
        self.horizontalLayout_b_18.addLayout(self.verticalLayout_b_8)
        self.verticalLayout_b_6.addLayout(self.horizontalLayout_b_18)

        self.updateb_b = QtGui.QPushButton(self.verticalLayoutWidget_b)
        self.updateb_b.setObjectName("updateb_b")
        self.verticalLayout_b_6.addWidget(self.updateb_b)

        self.horizontalLayout_b_19.addLayout(self.verticalLayout_b_6)
        self.verticalLayout_b_3 = QtGui.QVBoxLayout()
        self.verticalLayout_b_3.setObjectName(_fromUtf8("verticalLayout_b_3"))
        self.horizontalLayout_b_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_11.setObjectName(_fromUtf8("horizontalLayout_b_11"))
        self.horpl_b_6 = QtGui.QLabel(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_b_6.sizePolicy().hasHeightForWidth())
        self.horpl_b_6.setSizePolicy(sizePolicy)
        self.horpl_b_6.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_b_6.setObjectName(_fromUtf8("horpl_b_6"))
        self.horizontalLayout_b_11.addWidget(self.horpl_b_6)
        self.rv_b = QtGui.QLineEdit(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rv_b.sizePolicy().hasHeightForWidth())
        self.rv_b.setSizePolicy(sizePolicy)
        self.rv_b.setMaximumSize(QtCore.QSize(70, 16777215))
        self.rv_b.setObjectName(_fromUtf8("rv"))
        self.horizontalLayout_b_11.addWidget(self.rv_b, QtCore.Qt.AlignHCenter)
        self.horpl_b_17 = QtGui.QLabel(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_b_17.sizePolicy().hasHeightForWidth())
        self.horpl_b_17.setSizePolicy(sizePolicy)
        self.horpl_b_17.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_b_17.setText(_fromUtf8(""))
        self.horpl_b_17.setObjectName(_fromUtf8("horpl_b_17"))
        self.horizontalLayout_b_11.addWidget(self.horpl_b_17)
        self.verticalLayout_b_3.addLayout(self.horizontalLayout_b_11)
        self.dial_b = QtGui.QDial(self.verticalLayoutWidget_b)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_b.sizePolicy().hasHeightForWidth())
        self.dial_b.setSizePolicy(sizePolicy)
        self.dial_b.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.dial_b.setMaximum(360)
        self.dial_b.setProperty("value", 0)
        self.dial_b.setTracking(False)
        self.dial_b.setOrientation(QtCore.Qt.Vertical)
        self.dial_b.setWrapping(True)
        self.dial_b.setNotchTarget(5.0)
        self.dial_b.setNotchesVisible(True)
        self.dial_b.setObjectName(_fromUtf8("dial_b"))
        self.verticalLayout_b_3.addWidget(self.dial_b)
        self.horizontalLayout_b_19.addLayout(self.verticalLayout_b_3)
        self.verticalLayout_b.addLayout(self.horizontalLayout_b_19)
        self.horizontalLayout_b_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_b_6.setObjectName(_fromUtf8("horizontalLayout_b_6"))
        self.verticalLayout_b.addLayout(self.horizontalLayout_b_6)

        self.verticalLayoutWidget_c = QtGui.QWidget(self.tabWidgetPage3)
        self.verticalLayoutWidget_c.setGeometry(QtCore.QRect(40, 35, 400, 520))
        self.verticalLayoutWidget_c.setObjectName(_fromUtf8("verticalLayoutWidget_c"))
        self.verticalLayout_c = QtGui.QVBoxLayout(self.verticalLayoutWidget_c)
        self.verticalLayout_c.setObjectName(_fromUtf8("verticalLayout_c"))
        self.horizontalLayout_c_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_12.setObjectName(_fromUtf8("horizontalLayout_c_12"))
        self.horpl_c_12 = QtGui.QLabel(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_c_12.sizePolicy().hasHeightForWidth())
        self.horpl_c_12.setSizePolicy(sizePolicy)
        self.horpl_c_12.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_c_12.setObjectName(_fromUtf8("horpl_c_12"))
        self.horizontalLayout_c_12.addWidget(self.horpl_c_12)
        self.horv_c = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horv_c.sizePolicy().hasHeightForWidth())
        self.horv_c.setSizePolicy(sizePolicy)
        self.horv_c.setMaximumSize(QtCore.QSize(70, 16777215))
        self.horv_c.setObjectName(_fromUtf8("horv_c"))
        self.horizontalLayout_c_12.addWidget(self.horv_c, QtCore.Qt.AlignHCenter)
        self.horpl_c_18 = QtGui.QLabel(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_c_18.sizePolicy().hasHeightForWidth())
        self.horpl_c_18.setSizePolicy(sizePolicy)
        self.horpl_c_18.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_c_18.setText(_fromUtf8(""))
        self.horpl_c_18.setObjectName(_fromUtf8("horpl_c_18"))
        self.horizontalLayout_c_12.addWidget(self.horpl_c_18)
        self.verticalLayout_c.addLayout(self.horizontalLayout_c_12)
        self.horizontalLayout_c = QtGui.QHBoxLayout()
        self.horizontalLayout_c.setObjectName(_fromUtf8("horizontalLayout_c"))
        self.horpos_c_i = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpos_c_i.sizePolicy().hasHeightForWidth())
        self.horpos_c_i.setSizePolicy(sizePolicy)
        self.horpos_c_i.setMaximumSize(QtCore.QSize(50, 16777215))
        self.horpos_c_i.setObjectName(_fromUtf8("horpos_c_i"))
        self.horizontalLayout_c.addWidget(self.horpos_c_i)
        self.horpos_c_s = QtGui.QSlider(self.verticalLayoutWidget_c)
        self.horpos_c_s.setSliderPosition(50)
        self.horpos_c_s.setTracking(False)
        self.horpos_c_s.setOrientation(QtCore.Qt.Horizontal)
        self.horpos_c_s.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horpos_c_s.setTickInterval(1)
        self.horpos_c_s.setObjectName(_fromUtf8("horpos_c_s"))
        self.horizontalLayout_c.addWidget(self.horpos_c_s)
        self.horpos_c_a = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpos_c_a.sizePolicy().hasHeightForWidth())
        self.horpos_c_a.setSizePolicy(sizePolicy)
        self.horpos_c_a.setMaximumSize(QtCore.QSize(50, 16777215))
        self.horpos_c_a.setObjectName(_fromUtf8("horpos_c_a"))
        self.horizontalLayout_c.addWidget(self.horpos_c_a)
        self.verticalLayout_c.addLayout(self.horizontalLayout_c)
        spacerItem_c = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_c.addItem(spacerItem_c)
        self.horizontalLayout_c_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_7.setObjectName(_fromUtf8("horizontalLayout_c_7"))
        self.horpl_c_8 = QtGui.QLabel(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_c_8.sizePolicy().hasHeightForWidth())
        self.horpl_c_8.setSizePolicy(sizePolicy)
        self.horpl_c_8.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_c_8.setObjectName(_fromUtf8("horpl_c_8"))
        self.horizontalLayout_c_7.addWidget(self.horpl_c_8)
        self.hora_c = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hora_c.sizePolicy().hasHeightForWidth())
        self.hora_c.setSizePolicy(sizePolicy)
        self.hora_c.setMaximumSize(QtCore.QSize(70, 16777215))
        self.hora_c.setObjectName(_fromUtf8("hora_c"))
        self.horizontalLayout_c_7.addWidget(self.hora_c, QtCore.Qt.AlignHCenter)
        self.horpl_c_13 = QtGui.QLabel(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_c_13.sizePolicy().hasHeightForWidth())
        self.horpl_c_13.setSizePolicy(sizePolicy)
        self.horpl_c_13.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_c_13.setText(_fromUtf8(""))
        self.horpl_c_13.setObjectName(_fromUtf8("horpl_c_13"))
        self.horizontalLayout_c_7.addWidget(self.horpl_c_13)
        self.verticalLayout_c.addLayout(self.horizontalLayout_c_7)
        self.horizontalLayout_c_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_2.setObjectName(_fromUtf8("horizontalLayout_c_2"))
        self.horang_c_i = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horang_c_i.sizePolicy().hasHeightForWidth())
        self.horang_c_i.setSizePolicy(sizePolicy)
        self.horang_c_i.setMaximumSize(QtCore.QSize(50, 16777215))
        self.horang_c_i.setObjectName(_fromUtf8("horang_c_i"))
        self.horizontalLayout_c_2.addWidget(self.horang_c_i)
        self.horang_c_s = QtGui.QSlider(self.verticalLayoutWidget_c)
        self.horang_c_s.setSliderPosition(50)
        self.horang_c_s.setTracking(False)
        self.horang_c_s.setOrientation(QtCore.Qt.Horizontal)
        self.horang_c_s.setTickPosition(QtGui.QSlider.TicksBelow)
        self.horang_c_s.setTickInterval(1)
        self.horang_c_s.setObjectName(_fromUtf8("horang_c_s"))
        self.horizontalLayout_c_2.addWidget(self.horang_c_s)
        self.horang_c_a = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horang_c_a.sizePolicy().hasHeightForWidth())
        self.horang_c_a.setSizePolicy(sizePolicy)
        self.horang_c_a.setMinimumSize(QtCore.QSize(0, 0))
        self.horang_c_a.setMaximumSize(QtCore.QSize(50, 16777215))
        self.horang_c_a.setObjectName(_fromUtf8("horang_c_a"))
        self.horizontalLayout_c_2.addWidget(self.horang_c_a)
        self.verticalLayout_c.addLayout(self.horizontalLayout_c_2)
        spacerItem_c1 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_c.addItem(spacerItem_c1)
        self.horizontalLayout_c_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_8.setObjectName(_fromUtf8("horizontalLayout_c_8"))
        self.horpl_c_9 = QtGui.QLabel(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_c_9.sizePolicy().hasHeightForWidth())
        self.horpl_c_9.setSizePolicy(sizePolicy)
        self.horpl_c_9.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_c_9.setObjectName(_fromUtf8("horpl_c_9"))
        self.horizontalLayout_c_8.addWidget(self.horpl_c_9)
        self.verv_c = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verv_c.sizePolicy().hasHeightForWidth())
        self.verv_c.setSizePolicy(sizePolicy)
        self.verv_c.setMaximumSize(QtCore.QSize(70, 16777215))
        self.verv_c.setObjectName(_fromUtf8("verv_c"))
        self.horizontalLayout_c_8.addWidget(self.verv_c, QtCore.Qt.AlignHCenter)
        self.horpl_c_14 = QtGui.QLabel(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_c_14.sizePolicy().hasHeightForWidth())
        self.horpl_c_14.setSizePolicy(sizePolicy)
        self.horpl_c_14.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_c_14.setText(_fromUtf8(""))
        self.horpl_c_14.setObjectName(_fromUtf8("horpl_c_14"))
        self.horizontalLayout_c_8.addWidget(self.horpl_c_14)
        self.verticalLayout_c.addLayout(self.horizontalLayout_c_8)
        self.horizontalLayout_c_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_3.setObjectName(_fromUtf8("horizontalLayout_c_3"))
        self.verpos_c_i = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verpos_c_i.sizePolicy().hasHeightForWidth())
        self.verpos_c_i.setSizePolicy(sizePolicy)
        self.verpos_c_i.setMaximumSize(QtCore.QSize(50, 16777215))
        self.verpos_c_i.setObjectName(_fromUtf8("verpos_c_i"))
        self.horizontalLayout_c_3.addWidget(self.verpos_c_i)
        self.verpos_c_s = QtGui.QSlider(self.verticalLayoutWidget_c)
        self.verpos_c_s.setSliderPosition(50)
        self.verpos_c_s.setTracking(False)
        self.verpos_c_s.setOrientation(QtCore.Qt.Horizontal)
        self.verpos_c_s.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verpos_c_s.setTickInterval(1)
        self.verpos_c_s.setObjectName(_fromUtf8("verpos_c_s"))
        self.horizontalLayout_c_3.addWidget(self.verpos_c_s)
        self.verpos_c_a = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verpos_c_a.sizePolicy().hasHeightForWidth())
        self.verpos_c_a.setSizePolicy(sizePolicy)
        self.verpos_c_a.setMinimumSize(QtCore.QSize(0, 0))
        self.verpos_c_a.setMaximumSize(QtCore.QSize(50, 16777215))
        self.verpos_c_a.setObjectName(_fromUtf8("verpos_c_a"))
        self.horizontalLayout_c_3.addWidget(self.verpos_c_a)
        self.verticalLayout_c.addLayout(self.horizontalLayout_c_3)
        spacerItem_c2 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_c.addItem(spacerItem_c2)
        self.horizontalLayout_c_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_9.setObjectName(_fromUtf8("horizontalLayout_c_9"))
        self.horpl_c_10 = QtGui.QLabel(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_c_10.sizePolicy().hasHeightForWidth())
        self.horpl_c_10.setSizePolicy(sizePolicy)
        self.horpl_c_10.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_c_10.setObjectName(_fromUtf8("horpl_c_10"))
        self.horizontalLayout_c_9.addWidget(self.horpl_c_10)
        self.vera_c = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vera_c.sizePolicy().hasHeightForWidth())
        self.vera_c.setSizePolicy(sizePolicy)
        self.vera_c.setMaximumSize(QtCore.QSize(70, 16777215))
        self.vera_c.setObjectName(_fromUtf8("vera_c"))
        self.horizontalLayout_c_9.addWidget(self.vera_c, QtCore.Qt.AlignHCenter)
        self.horpl_c_15 = QtGui.QLabel(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_c_15.sizePolicy().hasHeightForWidth())
        self.horpl_c_15.setSizePolicy(sizePolicy)
        self.horpl_c_15.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_c_15.setText(_fromUtf8(""))
        self.horpl_c_15.setObjectName(_fromUtf8("horpl_c_15"))
        self.horizontalLayout_c_9.addWidget(self.horpl_c_15)
        self.verticalLayout_c.addLayout(self.horizontalLayout_c_9)
        self.horizontalLayout_c_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_4.setObjectName(_fromUtf8("horizontalLayout_c_4"))
        self.verang_c_i = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verang_c_i.sizePolicy().hasHeightForWidth())
        self.verang_c_i.setSizePolicy(sizePolicy)
        self.verang_c_i.setMaximumSize(QtCore.QSize(50, 16777215))
        self.verang_c_i.setObjectName(_fromUtf8("verang_c_i"))
        self.horizontalLayout_c_4.addWidget(self.verang_c_i)
        self.verang_c_s = QtGui.QSlider(self.verticalLayoutWidget_c)
        self.verang_c_s.setSliderPosition(50)
        self.verang_c_s.setTracking(False)
        self.verang_c_s.setOrientation(QtCore.Qt.Horizontal)
        self.verang_c_s.setTickPosition(QtGui.QSlider.TicksBelow)
        self.verang_c_s.setTickInterval(1)
        self.verang_c_s.setObjectName(_fromUtf8("verang_c_s"))
        self.horizontalLayout_c_4.addWidget(self.verang_c_s)
        self.verang_c_a = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verang_c_a.sizePolicy().hasHeightForWidth())
        self.verang_c_a.setSizePolicy(sizePolicy)
        self.verang_c_a.setMinimumSize(QtCore.QSize(0, 0))
        self.verang_c_a.setMaximumSize(QtCore.QSize(50, 16777215))
        self.verang_c_a.setObjectName(_fromUtf8("verang_c_a"))
        self.horizontalLayout_c_4.addWidget(self.verang_c_a)
        self.verticalLayout_c.addLayout(self.horizontalLayout_c_4)
        spacerItem_c3 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_c.addItem(spacerItem_c3)
        self.horizontalLayout_c_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_10.setObjectName(_fromUtf8("horizontalLayout_c_10"))
        self.horpl_c_11 = QtGui.QLabel(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_c_11.sizePolicy().hasHeightForWidth())
        self.horpl_c_11.setSizePolicy(sizePolicy)
        self.horpl_c_11.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_c_11.setObjectName(_fromUtf8("horpl_c_11"))
        self.horizontalLayout_c_10.addWidget(self.horpl_c_11)
        self.sv_c = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sv_c.sizePolicy().hasHeightForWidth())
        self.sv_c.setSizePolicy(sizePolicy)
        self.sv_c.setMaximumSize(QtCore.QSize(70, 16777215))
        self.sv_c.setObjectName(_fromUtf8("sv_c"))
        self.horizontalLayout_c_10.addWidget(self.sv_c, QtCore.Qt.AlignHCenter)
        self.horpl_c_16 = QtGui.QLabel(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_c_16.sizePolicy().hasHeightForWidth())
        self.horpl_c_16.setSizePolicy(sizePolicy)
        self.horpl_c_16.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_c_16.setText(_fromUtf8(""))
        self.horpl_c_16.setObjectName(_fromUtf8("horpl_c_16"))
        self.horizontalLayout_c_10.addWidget(self.horpl_c_16)
        self.verticalLayout_c.addLayout(self.horizontalLayout_c_10)
        self.horizontalLayout_c_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_5.setObjectName(_fromUtf8("horizontalLayout_c_5"))
        self.sizei_c = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizei_c.sizePolicy().hasHeightForWidth())
        self.sizei_c.setSizePolicy(sizePolicy)
        self.sizei_c.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sizei_c.setObjectName(_fromUtf8("sizei_c"))
        self.horizontalLayout_c_5.addWidget(self.sizei_c)
        self.sizes_c = QtGui.QSlider(self.verticalLayoutWidget_c)
        self.sizes_c.setSliderPosition(50)
        self.sizes_c.setTracking(False)
        self.sizes_c.setOrientation(QtCore.Qt.Horizontal)
        self.sizes_c.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sizes_c.setTickInterval(1)
        self.sizes_c.setObjectName(_fromUtf8("sizes_c"))
        self.horizontalLayout_c_5.addWidget(self.sizes_c)
        self.sizea_c = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizea_c.sizePolicy().hasHeightForWidth())
        self.sizea_c.setSizePolicy(sizePolicy)
        self.sizea_c.setMinimumSize(QtCore.QSize(0, 0))
        self.sizea_c.setMaximumSize(QtCore.QSize(50, 16777215))
        self.sizea_c.setObjectName(_fromUtf8("sizea_c"))
        self.horizontalLayout_c_5.addWidget(self.sizea_c)
        self.verticalLayout_c.addLayout(self.horizontalLayout_c_5)

        spacerItem_c7 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_c.addItem(spacerItem_c7)
        self.horizontalLayout_c_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_20.setObjectName(_fromUtf8("horizontalLayout_c_20"))
        self.horpl_c_20 = QtGui.QLabel(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_c_20.sizePolicy().hasHeightForWidth())
        self.horpl_c_20.setSizePolicy(sizePolicy)
        self.horpl_c_20.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_c_20.setObjectName(_fromUtf8("horpl_c_20"))
        self.horizontalLayout_c_20.addWidget(self.horpl_c_20)
        self.fv_c = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fv_c.sizePolicy().hasHeightForWidth())
        self.fv_c.setSizePolicy(sizePolicy)
        self.fv_c.setMaximumSize(QtCore.QSize(70, 16777215))
        self.fv_c.setObjectName(_fromUtf8("fv_c"))
        self.horizontalLayout_c_20.addWidget(self.fv_c, QtCore.Qt.AlignHCenter)
        self.horpl_c_21 = QtGui.QLabel(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_c_21.sizePolicy().hasHeightForWidth())
        self.horpl_c_21.setSizePolicy(sizePolicy)
        self.horpl_c_21.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_c_21.setText(_fromUtf8(""))
        self.horpl_c_21.setObjectName(_fromUtf8("horpl_c_21"))
        self.horizontalLayout_c_20.addWidget(self.horpl_c_21)
        self.verticalLayout_c.addLayout(self.horizontalLayout_c_20)
        self.horizontalLayout_c_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_21.setObjectName(_fromUtf8("horizontalLayout_c_21"))
        self.focus_c_i = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.focus_c_i.sizePolicy().hasHeightForWidth())
        self.focus_c_i.setSizePolicy(sizePolicy)
        self.focus_c_i.setMaximumSize(QtCore.QSize(50, 16777215))
        self.focus_c_i.setObjectName(_fromUtf8("focus_c_i"))
        self.horizontalLayout_c_21.addWidget(self.focus_c_i)
        self.focus_c_s = QtGui.QSlider(self.verticalLayoutWidget_c)
        self.focus_c_s.setSliderPosition(50)
        self.focus_c_s.setTracking(False)
        self.focus_c_s.setOrientation(QtCore.Qt.Horizontal)
        self.focus_c_s.setTickPosition(QtGui.QSlider.TicksBelow)
        self.focus_c_s.setTickInterval(1)
        self.focus_c_s.setObjectName(_fromUtf8("focus_c_s"))
        self.horizontalLayout_c_21.addWidget(self.focus_c_s)
        self.focus_c_a = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.focus_c_a.sizePolicy().hasHeightForWidth())
        self.focus_c_a.setSizePolicy(sizePolicy)
        self.focus_c_a.setMinimumSize(QtCore.QSize(0, 0))
        self.focus_c_a.setMaximumSize(QtCore.QSize(50, 16777215))
        self.focus_c_a.setObjectName(_fromUtf8("focus_c_a"))
        self.horizontalLayout_c_21.addWidget(self.focus_c_a)
        self.verticalLayout_c.addLayout(self.horizontalLayout_c_21)

        spacerItem_c4 = QtGui.QSpacerItem(416, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_c.addItem(spacerItem_c4)
        self.horizontalLayout_c_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_19.setObjectName(_fromUtf8("horizontalLayout_c_19"))
        self.verticalLayout_c_6 = QtGui.QVBoxLayout()
        self.verticalLayout_c_6.setObjectName(_fromUtf8("verticalLayout_c_6"))
        self.horizontalLayout_c_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_18.setObjectName(_fromUtf8("horizontalLayout_c_18"))
        self.verticalLayout_c_7 = QtGui.QVBoxLayout()
        self.verticalLayout_c_7.setObjectName(_fromUtf8("verticalLayout_c_7"))
        self.label_2_c = QtGui.QLabel(self.verticalLayoutWidget_c)
        self.label_2_c.setObjectName(_fromUtf8("label_2_c"))
        self.verticalLayout_c_7.addWidget(self.label_2_c)
        self.lbox_c = QtGui.QSpinBox(self.verticalLayoutWidget_c)
        self.lbox_c.setObjectName(_fromUtf8("lbox_c"))
        self.verticalLayout_c_7.addWidget(self.lbox_c)
        spacerItem_c5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_c_7.addItem(spacerItem_c5)
        self.horizontalLayout_c_18.addLayout(self.verticalLayout_c_7)
        self.verticalLayout_c_8 = QtGui.QVBoxLayout()
        self.verticalLayout_c_8.setObjectName(_fromUtf8("verticalLayout_c_8"))
        self.label_3_c = QtGui.QLabel(self.verticalLayoutWidget_c)
        self.label_3_c.setObjectName(_fromUtf8("label_3_c"))
        self.verticalLayout_c_8.addWidget(self.label_3_c)
        self.gbox_c = QtGui.QSpinBox(self.verticalLayoutWidget_c)
        self.gbox_c.setObjectName(_fromUtf8("gbox_c"))
        self.verticalLayout_c_8.addWidget(self.gbox_c)
        spacerItem_c6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_c_8.addItem(spacerItem_c6)
        self.horizontalLayout_c_18.addLayout(self.verticalLayout_c_8)
        self.verticalLayout_c_6.addLayout(self.horizontalLayout_c_18)

        self.updateb_c = QtGui.QPushButton(self.verticalLayoutWidget_c)
        self.updateb_c.setObjectName("updateb_c")
        self.verticalLayout_c_6.addWidget(self.updateb_c)

        self.horizontalLayout_c_19.addLayout(self.verticalLayout_c_6)
        self.verticalLayout_c_3 = QtGui.QVBoxLayout()
        self.verticalLayout_c_3.setObjectName(_fromUtf8("verticalLayout_c_3"))
        self.horizontalLayout_c_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_11.setObjectName(_fromUtf8("horizontalLayout_c_11"))
        self.horpl_c_6 = QtGui.QLabel(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_c_6.sizePolicy().hasHeightForWidth())
        self.horpl_c_6.setSizePolicy(sizePolicy)
        self.horpl_c_6.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_c_6.setObjectName(_fromUtf8("horpl_c_6"))
        self.horizontalLayout_c_11.addWidget(self.horpl_c_6)
        self.rv_c = QtGui.QLineEdit(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rv_c.sizePolicy().hasHeightForWidth())
        self.rv_c.setSizePolicy(sizePolicy)
        self.rv_c.setMaximumSize(QtCore.QSize(70, 16777215))
        self.rv_c.setObjectName(_fromUtf8("rv"))
        self.horizontalLayout_c_11.addWidget(self.rv_c, QtCore.Qt.AlignHCenter)
        self.horpl_c_17 = QtGui.QLabel(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horpl_c_17.sizePolicy().hasHeightForWidth())
        self.horpl_c_17.setSizePolicy(sizePolicy)
        self.horpl_c_17.setMinimumSize(QtCore.QSize(100, 0))
        self.horpl_c_17.setText(_fromUtf8(""))
        self.horpl_c_17.setObjectName(_fromUtf8("horpl_c_17"))
        self.horizontalLayout_c_11.addWidget(self.horpl_c_17)
        self.verticalLayout_c_3.addLayout(self.horizontalLayout_c_11)
        self.dial_c = QtGui.QDial(self.verticalLayoutWidget_c)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dial_c.sizePolicy().hasHeightForWidth())
        self.dial_c.setSizePolicy(sizePolicy)
        self.dial_c.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.dial_c.setMaximum(360)
        self.dial_c.setProperty("value", 0)
        self.dial_c.setTracking(False)
        self.dial_c.setOrientation(QtCore.Qt.Vertical)
        self.dial_c.setWrapping(True)
        self.dial_c.setNotchTarget(5.0)
        self.dial_c.setNotchesVisible(True)
        self.dial_c.setObjectName(_fromUtf8("dial_c"))
        self.verticalLayout_c_3.addWidget(self.dial_c)
        self.horizontalLayout_c_19.addLayout(self.verticalLayout_c_3)
        self.verticalLayout_c.addLayout(self.horizontalLayout_c_19)
        self.horizontalLayout_c_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_c_6.setObjectName(_fromUtf8("horizontalLayout_c_6"))
        self.verticalLayout_c.addLayout(self.horizontalLayout_c_6)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tabWidget.addTab(self.tabWidgetPage3, "")


        self.timel = QtGui.QLabel(self.centralwidget)
        self.timel.setGeometry(QtCore.QRect(40,640, 120, 30))
        self.timel.setText(_fromUtf8(""))
        self.timel.setObjectName(_fromUtf8("timel"))
        self.timev = QtGui.QLineEdit(self.centralwidget)
        self.timev.setGeometry(QtCore.QRect(170,640,70,30))
        self.timev.setObjectName(_fromUtf8("timev"))


        self.sendb = QtGui.QPushButton(self.centralwidget)
        self.sendb.setGeometry(QtCore.QRect(280, 640, 100, 30))
        self.sendb.setObjectName("sendb")
        self.pauseb = QtGui.QPushButton(self.centralwidget)
        self.pauseb.setGeometry(QtCore.QRect(390, 640, 100, 30))
        self.pauseb.setObjectName("pauseb")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SLM LOOP Control", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWindow", "1st Mode",None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("MainWindow", "2nd Mode",None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), _translate("MainWindow", "3rd Mode",None))

        self.horpl_12.setText(_translate("MainWindow", "Horizontal Position:", None))
        self.horv.setText(_translate("MainWindow", "0", None))
        self.horposi.setText(_translate("MainWindow", "-50", None))
        self.horposa.setText(_translate("MainWindow", "50", None))
        self.horpl_8.setText(_translate("MainWindow", "Horizontal Angle:", None))
        self.hora.setText(_translate("MainWindow", "0", None))
        self.horangi.setText(_translate("MainWindow", "-15", None))
        self.horanga.setText(_translate("MainWindow", "15", None))
        self.horpl_9.setText(_translate("MainWindow", "Vertical Position:", None))
        self.verv.setText(_translate("MainWindow", "0", None))
        self.verposi.setText(_translate("MainWindow", "-50", None))
        self.verposa.setText(_translate("MainWindow", "50", None))
        self.horpl_10.setText(_translate("MainWindow", "Vertical Angle:", None))
        self.vera.setText(_translate("MainWindow", "0", None))
        self.verangi.setText(_translate("MainWindow", "-15", None))
        self.veranga.setText(_translate("MainWindow", "15", None))
        self.horpl_11.setText(_translate("MainWindow", "Size:", None))
        self.sv.setText(_translate("MainWindow", "0", None))
        self.sizei.setText(_translate("MainWindow", "0", None))
        self.sizea.setText(_translate("MainWindow", "300", None))
        self.horpl_20.setText(_translate("MainWindow", "Focus:", None))
        self.fv.setText(_translate("MainWindow", "0", None))
        self.focusi.setText(_translate("MainWindow", "-0.1", None))
        self.focusa.setText(_translate("MainWindow", "0.1", None))
        self.label_2.setText(_translate("MainWindow", "L:", None))
        self.label_3.setText(_translate("MainWindow", "G:", None))
        self.horpl_6.setText(_translate("MainWindow", "Rotation:", None))
        self.rv.setText(_translate("MainWindow", "0", None))

        self.horpl_b_12.setText(_translate("MainWindow", "Horizontal Position:", None))
        self.horv_b.setText(_translate("MainWindow", "0", None))
        self.horpos_b_i.setText(_translate("MainWindow", "-50", None))
        self.horpos_b_a.setText(_translate("MainWindow", "50", None))
        self.horpl_b_8.setText(_translate("MainWindow", "Horizontal Angle:", None))
        self.hora_b.setText(_translate("MainWindow", "0", None))
        self.horang_b_i.setText(_translate("MainWindow", "-15", None))
        self.horang_b_a.setText(_translate("MainWindow", "15", None))
        self.horpl_b_9.setText(_translate("MainWindow", "Vertical Position:", None))
        self.verv_b.setText(_translate("MainWindow", "0", None))
        self.verpos_b_i.setText(_translate("MainWindow", "-50", None))
        self.verpos_b_a.setText(_translate("MainWindow", "50", None))
        self.horpl_b_10.setText(_translate("MainWindow", "Vertical Angle:", None))
        self.vera_b.setText(_translate("MainWindow", "0", None))
        self.verang_b_i.setText(_translate("MainWindow", "-15", None))
        self.verang_b_a.setText(_translate("MainWindow", "15", None))
        self.horpl_b_11.setText(_translate("MainWindow", "Size:", None))
        self.sv_b.setText(_translate("MainWindow", "0", None))
        self.sizei_b.setText(_translate("MainWindow", "0", None))
        self.sizea_b.setText(_translate("MainWindow", "300", None))
        self.horpl_b_20.setText(_translate("MainWindow", "Focus:", None))
        self.fv_b.setText(_translate("MainWindow", "0", None))
        self.focus_b_i.setText(_translate("MainWindow", "-0.1", None))
        self.focus_b_a.setText(_translate("MainWindow", "0.1", None))
        self.label_2_b.setText(_translate("MainWindow", "L:", None))
        self.label_3_b.setText(_translate("MainWindow", "G:", None))
        self.horpl_b_6.setText(_translate("MainWindow", "Rotation:", None))
        self.rv_b.setText(_translate("MainWindow", "0", None))

        self.horpl_c_12.setText(_translate("MainWindow", "Horizontal Position:", None))
        self.horv_c.setText(_translate("MainWindow", "0", None))
        self.horpos_c_i.setText(_translate("MainWindow", "-50", None))
        self.horpos_c_a.setText(_translate("MainWindow", "50", None))
        self.horpl_c_8.setText(_translate("MainWindow", "Horizontal Angle:", None))
        self.hora_c.setText(_translate("MainWindow", "0", None))
        self.horang_c_i.setText(_translate("MainWindow", "-15", None))
        self.horang_c_a.setText(_translate("MainWindow", "15", None))
        self.horpl_c_9.setText(_translate("MainWindow", "Vertical Position:", None))
        self.verv_c.setText(_translate("MainWindow", "0", None))
        self.verpos_c_i.setText(_translate("MainWindow", "-50", None))
        self.verpos_c_a.setText(_translate("MainWindow", "50", None))
        self.horpl_c_10.setText(_translate("MainWindow", "Vertical Angle:", None))
        self.vera_c.setText(_translate("MainWindow", "0", None))
        self.verang_c_i.setText(_translate("MainWindow", "-15", None))
        self.verang_c_a.setText(_translate("MainWindow", "15", None))
        self.horpl_c_11.setText(_translate("MainWindow", "Size:", None))
        self.sv_c.setText(_translate("MainWindow", "0", None))
        self.sizei_c.setText(_translate("MainWindow", "0", None))
        self.sizea_c.setText(_translate("MainWindow", "300", None))
        self.horpl_c_20.setText(_translate("MainWindow", "Focus:", None))
        self.fv_c.setText(_translate("MainWindow", "0", None))
        self.focus_c_i.setText(_translate("MainWindow", "-0.1", None))
        self.focus_c_a.setText(_translate("MainWindow", "0.1", None))
        self.label_2_c.setText(_translate("MainWindow", "L:", None))
        self.label_3_c.setText(_translate("MainWindow", "G:", None))
        self.horpl_c_6.setText(_translate("MainWindow", "Rotation:", None))
        self.rv_c.setText(_translate("MainWindow", "0", None))

        self.timel.setText(_translate("MainWindow", "Time intervals:", None))
        self.timev.setText(_translate("MainWindow", "1.0", None))
        self.sendb.setText(_translate("MainWindow", "Send", None))
        self.pauseb.setText(_translate("MainWindow", "Pause", None))

        self.updateb.setText(_translate("MainWindow", "Update", None))
        self.updateb_b.setText(_translate("MainWindow", "Update", None))
        self.updateb_c.setText(_translate("MainWindow", "Update", None))

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
